sonar.organization=andrest3009
sonar.projectKey=AndresT3009_tractor-store-frontend

sonar.sources=apps,packages
sonar.tests=apps,packages
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/dist/**,**/*.spec.ts,**/*.stories.ts,**/.storybook/**,**/jest.config.ts,**/federation.config.js

sonar.javascript.lcov.reportPaths=coverage/**/lcov.info
